/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CategoryModify;
import controller.OrderModify;
import controller.OrderProductModify;
import controller.ProductModify;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Category;
import model.Order;
import model.OrderProduct;
import model.Product;

/**
 *
 * @author Admin
 */
public class OrderProductFrm extends javax.swing.JDialog {

    /**
     * Creates new form OrderProductFrm
     */
    
    DefaultTableModel tableModelOrderProduct;
    
    List<OrderProduct> productOrderList = new ArrayList<>();
    List<Category> categoryList = new ArrayList<>();
    List<Product> productList = new ArrayList<>();
    
    int user_id;
    
    public OrderProductFrm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        tableModelOrderProduct = (DefaultTableModel) tableOrderProduct.getModel();
        
        tableOrderProduct.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
            }

            @Override
            public void mousePressed(MouseEvent e) {
                int selectedIndex = tableOrderProduct.getSelectedRow();
                OrderProduct orderProduct = productOrderList.get(selectedIndex);
                
                txtNameOrderPrd.setText(orderProduct.getUser_name());
                boxProduct.setSelectedItem(orderProduct.getProduct_name());
                boxNameCat.setSelectedItem(orderProduct.getCategory_name());
                txtPriceOrderPrd.setText(orderProduct.getPrice());
                txtCountOrderPrd.setText(String.valueOf(orderProduct.getCount()));
                
                btnDeleteOrderPrd.setEnabled(true);
                btnUpdateOrderPrd.setEnabled(true);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        
        });
        
        showComboBox_Category();
        showComboBox_Product();
    }
    
    public void showComboBox_Category() {
        DefaultComboBoxModel<String> comboBoxModelOrderProduct = (DefaultComboBoxModel<String>) boxNameCat.getModel();
        comboBoxModelOrderProduct.removeAllElements();
        categoryList = CategoryModify.findAll();
        categoryList.forEach(category -> {
            comboBoxModelOrderProduct.addElement(category.getName());
        });
    }
    
    public void showComboBox_Product() {
        DefaultComboBoxModel<String> comboBoxModelOrderProduct = (DefaultComboBoxModel<String>) boxProduct.getModel();
        comboBoxModelOrderProduct.removeAllElements();
        productList = ProductModify.findAll();
        productList.forEach(prd -> {
            comboBoxModelOrderProduct.addElement(prd.getTitle());
        });
    }
    
    public void showComboBox_Product_findByCat(String name_cat) {
        DefaultComboBoxModel<String> comboBoxModelOrderProduct = (DefaultComboBoxModel<String>) boxProduct.getModel();
        comboBoxModelOrderProduct.removeAllElements();
        productList = ProductModify.findByCat(name_cat);
        productList.forEach(prd -> {
            comboBoxModelOrderProduct.addElement(prd.getTitle());
        });
    }
    
    private void showOrderProduct(int user_id) {
        productOrderList = OrderProductModify.findAll(user_id);
        tableModelOrderProduct.setRowCount(0);
        
        productOrderList.forEach((prd) -> {
            tableModelOrderProduct.addRow(new Object[] {
                tableModelOrderProduct.getRowCount() + 1,
                prd.getUser_name(),
                prd.getProduct_name(),
                prd.getCategory_name(),
                prd.getPrice(),
                prd.getCount()
            });
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNameOrderPrd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPriceOrderPrd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCountOrderPrd = new javax.swing.JTextField();
        boxNameCat = new javax.swing.JComboBox<>();
        btnInsertOrderPrd = new javax.swing.JButton();
        btnUpdateOrderPrd = new javax.swing.JButton();
        btnDeleteOrderPrd = new javax.swing.JButton();
        btnResetOrderPrd = new javax.swing.JButton();
        boxProduct = new javax.swing.JComboBox<>();
        btnExitOrderPrd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOrderProduct = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tên khách hàng:");

        txtNameOrderPrd.setEnabled(false);

        jLabel2.setText("Tên sản phẩm:");

        jLabel3.setText("Danh mục:");

        jLabel4.setText("Giá tiền:");

        jLabel5.setText("Số lượng:");

        txtCountOrderPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountOrderPrdActionPerformed(evt);
            }
        });

        boxNameCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNameCatActionPerformed(evt);
            }
        });

        btnInsertOrderPrd.setText("Thêm");
        btnInsertOrderPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertOrderPrdActionPerformed(evt);
            }
        });

        btnUpdateOrderPrd.setText("Sửa");
        btnUpdateOrderPrd.setEnabled(false);
        btnUpdateOrderPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderPrdActionPerformed(evt);
            }
        });

        btnDeleteOrderPrd.setText("Xóa");
        btnDeleteOrderPrd.setEnabled(false);
        btnDeleteOrderPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderPrdActionPerformed(evt);
            }
        });

        btnResetOrderPrd.setText("Reset");
        btnResetOrderPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetOrderPrdActionPerformed(evt);
            }
        });

        btnExitOrderPrd.setText("Thoát");
        btnExitOrderPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitOrderPrdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(txtCountOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(txtPriceOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(txtNameOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boxNameCat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(86, 86, 86)))))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsertOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExitOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdateOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxNameCat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPriceOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExitOrderPrd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tableOrderProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên khách hàng", "Tên sản phẩm", "Tên danh mục", "Giá tiền", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(tableOrderProduct);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertOrderPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertOrderPrdActionPerformed
        // TODO add your handling code here:
        
        String product_title;
        int product_id = 0, count = 0;
        product_title = boxProduct.getSelectedItem().toString();
        productList = ProductModify.findAll();
        for(Product product : productList) {
            if(product.getTitle().equals(product_title)) {
                product_id = product.getId();
            }
        }
        
        if(txtCountOrderPrd.getText().length() >= 0) {
            count = Integer.parseInt(txtCountOrderPrd.getText());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa điền số lượng!");
        }
        
        OrderProduct orderProduct = new OrderProduct(user_id, product_id, count, 1);
        OrderProductModify.insert(orderProduct);
        
        btnUpdateOrderPrd.setEnabled(false);
        btnDeleteOrderPrd.setEnabled(false);
        
        showOrderProduct(user_id);
        OrderModify.update_total(user_id);
   
    }//GEN-LAST:event_btnInsertOrderPrdActionPerformed

    private void btnUpdateOrderPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderPrdActionPerformed
        // TODO add your handling code here:
        String user_name = null, product_name = null, category_name = null, price = null;
        int idCat = 0;
        int idPrd = 0;
        int count = 0;
        boolean isOK = true;
        int selectedIndex = tableOrderProduct.getSelectedRow();
        if(selectedIndex >= 0) {

            
            product_name = boxProduct.getSelectedItem().toString();
            for(Product prd : productList) {
                if(prd.getTitle().equals(product_name)) {
                    idPrd = prd.getId();
                }
            }
            
            if(txtCountOrderPrd.getText().length() > 0) {
                count = Integer.parseInt(txtCountOrderPrd.getText());
            } else {
                isOK = false;
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập số lượng sản phẩm");
            }

            if(isOK) {
                OrderProduct orderProduct1 = productOrderList.get(selectedIndex);
                OrderProduct orderProduct = new OrderProduct(orderProduct1.getId(), idPrd, count);
                OrderProductModify.update(orderProduct);
                JOptionPane.showMessageDialog(rootPane, "Bạn đã cập nhật thành công!");
            }
        }

        txtNameOrderPrd.setText("");
        boxNameCat.setSelectedIndex(0);
        txtPriceOrderPrd.setText("");
        txtCountOrderPrd.setText("");
        boxProduct.setSelectedIndex(0);

        btnUpdateOrderPrd.setEnabled(false);
        btnDeleteOrderPrd.setEnabled(false);
        showOrderProduct(user_id);
        OrderModify.update_total(user_id);
    }//GEN-LAST:event_btnUpdateOrderPrdActionPerformed

    private void btnDeleteOrderPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderPrdActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tableOrderProduct.getSelectedRow();
        if (selectedIndex >= 0 ){
            OrderProduct orderProduct = productOrderList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Ban có chắc chắn muốn xóa không?");

            if(option == 0){
                ProductModify.delete(orderProduct.getId());

                txtNameOrderPrd.setText("");
                boxNameCat.setSelectedIndex(0);
                boxProduct.setSelectedIndex(0);
                txtPriceOrderPrd.setText("");
                txtCountOrderPrd.setText("");

                btnDeleteOrderPrd.setEnabled(false);
                btnUpdateOrderPrd.setEnabled(false);
                JOptionPane.showMessageDialog(rootPane, "Bạn đã xóa thành công");
                showOrderProduct(user_id);
                OrderModify.update_total(user_id);
            }
        }
    }//GEN-LAST:event_btnDeleteOrderPrdActionPerformed

    private void btnResetOrderPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetOrderPrdActionPerformed
        // TODO add your handling code here:
            txtNameOrderPrd.setText("");
            boxNameCat.setSelectedIndex(0);
            boxProduct.setSelectedIndex(0);
            txtPriceOrderPrd.setText("");
            txtCountOrderPrd.setText("");

            btnDeleteOrderPrd.setEnabled(false);
            btnUpdateOrderPrd.setEnabled(false);
        showOrderProduct(user_id);
    }//GEN-LAST:event_btnResetOrderPrdActionPerformed

    private void boxNameCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNameCatActionPerformed
        // TODO add your handling code here:
        showComboBox_Product_findByCat(boxNameCat.getSelectedItem().toString());
    }//GEN-LAST:event_boxNameCatActionPerformed

    private void btnExitOrderPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitOrderPrdActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitOrderPrdActionPerformed

    private void txtCountOrderPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountOrderPrdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountOrderPrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderProductFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderProductFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderProductFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderProductFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OrderProductFrm dialog = new OrderProductFrm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxNameCat;
    private javax.swing.JComboBox<String> boxProduct;
    private javax.swing.JButton btnDeleteOrderPrd;
    private javax.swing.JButton btnExitOrderPrd;
    private javax.swing.JButton btnInsertOrderPrd;
    private javax.swing.JButton btnResetOrderPrd;
    private javax.swing.JButton btnUpdateOrderPrd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableOrderProduct;
    private javax.swing.JTextField txtCountOrderPrd;
    private javax.swing.JTextField txtNameOrderPrd;
    private javax.swing.JTextField txtPriceOrderPrd;
    // End of variables declaration//GEN-END:variables

    void getUser_id(Order order) {
        user_id = order.getUser_id();
        showOrderProduct(user_id);
    }

}
